services:
  # mysql database
  db:
    build: ./db
    ports:
      - 3306:3306
      - 33060:33060
    command: mysqld --sql_mode="" --max_allowed_packet=32505856 --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=application
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=appuserpassword

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on: [db]
    ports: [8081:80]
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - PMA_HOST=db

  # redis
  redis:
    image: redis:latest
    ports: 
      - 6379:6379
    command: redis-server --requirepass redispassword

  # api
  api:
    depends_on: [db, phpmyadmin, redis]
    build: ./api
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=db
      - DB_PORT=3306

  # client
  client:
    depends_on: [api]
    build: ./client
    ports:
      - 8000:80
